import { FlatCompat } from '@eslint/eslintrc';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
import tseslint from 'typescript-eslint';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = tseslint.config(
  // Ignore patterns
  {
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'dist/**',
      'build/**',
      '*.config.js',
      '*.config.mjs',
      '*.config.ts',
      'next-env.d.ts', // Auto-generated by Next.js
    ],
  },

  // Next.js base rules
  ...compat.extends('next/core-web-vitals', 'next/typescript'),

  // TypeScript strict rules
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,

  // Parser options for type-aware linting
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
  },

  // Custom rules
  {
    rules: {
      // ============================================
      // REACT HOOKS - Critical for catching bugs
      // ============================================
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'warn',

      // ============================================
      // TYPESCRIPT - Strict but practical
      // ============================================

      // Unused variables - error, but allow underscore prefix
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],

      // Require explicit return types on exported functions (catches bugs)
      '@typescript-eslint/explicit-function-return-type': ['warn', {
        allowExpressions: true,
        allowTypedFunctionExpressions: true,
        allowHigherOrderFunctions: true,
        allowDirectConstAssertionInArrowFunctions: true,
        allowConciseArrowFunctionExpressionsStartingWithVoid: true,
      }],

      // No floating promises (catches forgotten awaits)
      '@typescript-eslint/no-floating-promises': 'error',

      // No misused promises (catches async bugs)
      '@typescript-eslint/no-misused-promises': ['error', {
        checksVoidReturn: {
          arguments: false, // Allow async onClick handlers
          attributes: false,
        },
      }],

      // Require await for async functions
      '@typescript-eslint/require-await': 'warn',

      // Consistent type imports
      '@typescript-eslint/consistent-type-imports': ['error', {
        prefer: 'type-imports',
        fixStyle: 'inline-type-imports',
      }],

      // Allow empty functions (sometimes needed for defaults)
      '@typescript-eslint/no-empty-function': 'off',

      // Allow non-null assertions when you know better
      '@typescript-eslint/no-non-null-assertion': 'warn',

      // Relax some overly strict rules
      '@typescript-eslint/no-unnecessary-condition': 'off', // Too many false positives
      '@typescript-eslint/restrict-template-expressions': 'off', // Too strict for practical use
      '@typescript-eslint/no-confusing-void-expression': 'off', // Annoying with arrow functions

      // ============================================
      // GENERAL JAVASCRIPT
      // ============================================

      // No console.log in production (warn, not error)
      'no-console': ['warn', { allow: ['warn', 'error'] }],

      // Require === instead of ==
      'eqeqeq': ['error', 'always', { null: 'ignore' }],

      // No var, use let/const
      'no-var': 'error',

      // Prefer const when not reassigning
      'prefer-const': 'error',

      // No duplicate imports
      'no-duplicate-imports': 'error',

      // ============================================
      // REACT / JSX
      // ============================================

      // Allow JSX in .tsx files
      'react/jsx-filename-extension': ['error', { extensions: ['.tsx', '.jsx'] }],

      // Don't require React import (Next.js handles it)
      'react/react-in-jsx-scope': 'off',

      // Allow spreading props (sometimes necessary)
      'react/jsx-props-no-spreading': 'off',

      // Require key in iterators
      'react/jsx-key': ['error', { checkFragmentShorthand: true }],

      // No array index as key (causes bugs)
      'react/no-array-index-key': 'warn',

      // ============================================
      // IMPORTS (optional but nice)
      // ============================================

      // Sort imports would go here if you want it
      // Requires eslint-plugin-import
    },
  },

  // Disable type-aware rules for config files (they don't have tsconfig)
  {
    files: ['**/*.js', '**/*.mjs', '**/*.cjs'],
    ...tseslint.configs.disableTypeChecked,
  },
);

export default eslintConfig;
