/**
 * UnderFireAI Database Types
 *
 * Top section: auto-generated by `npx supabase gen types typescript`
 * Bottom section: hand-written convenience interfaces for application code
 */

// ============================================
// GENERATED TYPES (from Supabase CLI)
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      interview_messages: {
        Row: {
          analysis: Json | null
          audio_url: string | null
          content: string
          created_at: string
          id: string
          response_time_seconds: number | null
          role: Database["public"]["Enums"]["message_role"]
          session_id: string
        }
        Insert: {
          analysis?: Json | null
          audio_url?: string | null
          content: string
          created_at?: string
          id?: string
          response_time_seconds?: number | null
          role: Database["public"]["Enums"]["message_role"]
          session_id: string
        }
        Update: {
          analysis?: Json | null
          audio_url?: string | null
          content?: string
          created_at?: string
          id?: string
          response_time_seconds?: number | null
          role?: Database["public"]["Enums"]["message_role"]
          session_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "interview_messages_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "interview_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      interview_sessions: {
        Row: {
          difficulty: number
          duration_seconds: number | null
          ended_at: string | null
          id: string
          interview_type: Database["public"]["Enums"]["interview_type"]
          interviewer_id: string
          max_user_messages: number | null
          session_length: Database["public"]["Enums"]["session_length"] | null
          started_at: string
          status: Database["public"]["Enums"]["session_status"]
          target_company: string | null
          target_role: string | null
          user_id: string
          voice_enabled: boolean
        }
        Insert: {
          difficulty?: number
          duration_seconds?: number | null
          ended_at?: string | null
          id?: string
          interview_type: Database["public"]["Enums"]["interview_type"]
          interviewer_id: string
          max_user_messages?: number | null
          session_length?: Database["public"]["Enums"]["session_length"] | null
          started_at?: string
          status?: Database["public"]["Enums"]["session_status"]
          target_company?: string | null
          target_role?: string | null
          user_id: string
          voice_enabled?: boolean
        }
        Update: {
          difficulty?: number
          duration_seconds?: number | null
          ended_at?: string | null
          id?: string
          interview_type?: Database["public"]["Enums"]["interview_type"]
          interviewer_id?: string
          max_user_messages?: number | null
          session_length?: Database["public"]["Enums"]["session_length"] | null
          started_at?: string
          status?: Database["public"]["Enums"]["session_status"]
          target_company?: string | null
          target_role?: string | null
          user_id?: string
          voice_enabled?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "interview_sessions_interviewer_id_fkey"
            columns: ["interviewer_id"]
            isOneToOne: false
            referencedRelation: "interviewers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interview_sessions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      interviewer_personality: {
        Row: {
          communication_style: Json | null
          created_at: string
          favorite_topics: string[] | null
          green_flags: string[] | null
          hidden_preferences: Json | null
          id: string
          interviewer_id: string
          mood_triggers: Json | null
          pet_peeves: string[] | null
          question_patterns: Json | null
          red_flags: string[] | null
        }
        Insert: {
          communication_style?: Json | null
          created_at?: string
          favorite_topics?: string[] | null
          green_flags?: string[] | null
          hidden_preferences?: Json | null
          id?: string
          interviewer_id: string
          mood_triggers?: Json | null
          pet_peeves?: string[] | null
          question_patterns?: Json | null
          red_flags?: string[] | null
        }
        Update: {
          communication_style?: Json | null
          created_at?: string
          favorite_topics?: string[] | null
          green_flags?: string[] | null
          hidden_preferences?: Json | null
          id?: string
          interviewer_id?: string
          mood_triggers?: Json | null
          pet_peeves?: string[] | null
          question_patterns?: Json | null
          red_flags?: string[] | null
        }
        Relationships: [
          {
            foreignKeyName: "interviewer_personality_interviewer_id_fkey"
            columns: ["interviewer_id"]
            isOneToOne: true
            referencedRelation: "interviewers"
            referencedColumns: ["id"]
          },
        ]
      }
      interviewers: {
        Row: {
          avatar_url: string | null
          backstory: string | null
          company_style: Database["public"]["Enums"]["company_style"] | null
          created_at: string
          current_mood: Json | null
          difficulty_level: number
          id: string
          interview_type: Database["public"]["Enums"]["interview_type"]
          name: string
          personality_base: Json | null
          role_focus: string | null
          total_sessions: number
          user_id: string
          voice_config: Json | null
        }
        Insert: {
          avatar_url?: string | null
          backstory?: string | null
          company_style?: Database["public"]["Enums"]["company_style"] | null
          created_at?: string
          current_mood?: Json | null
          difficulty_level?: number
          id?: string
          interview_type: Database["public"]["Enums"]["interview_type"]
          name: string
          personality_base?: Json | null
          role_focus?: string | null
          total_sessions?: number
          user_id: string
          voice_config?: Json | null
        }
        Update: {
          avatar_url?: string | null
          backstory?: string | null
          company_style?: Database["public"]["Enums"]["company_style"] | null
          created_at?: string
          current_mood?: Json | null
          difficulty_level?: number
          id?: string
          interview_type?: Database["public"]["Enums"]["interview_type"]
          name?: string
          personality_base?: Json | null
          role_focus?: string | null
          total_sessions?: number
          user_id?: string
          voice_config?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "interviewers_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          full_name: string | null
          id: string
          monthly_interviews_used: number
          onboarding_completed: boolean
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          subscription_period_end: string | null
          subscription_status: Database["public"]["Enums"]["subscription_status"]
          subscription_tier: Database["public"]["Enums"]["subscription_tier"]
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          full_name?: string | null
          id: string
          monthly_interviews_used?: number
          onboarding_completed?: boolean
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_period_end?: string | null
          subscription_status?: Database["public"]["Enums"]["subscription_status"]
          subscription_tier?: Database["public"]["Enums"]["subscription_tier"]
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          monthly_interviews_used?: number
          onboarding_completed?: boolean
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          subscription_period_end?: string | null
          subscription_status?: Database["public"]["Enums"]["subscription_status"]
          subscription_tier?: Database["public"]["Enums"]["subscription_tier"]
          updated_at?: string
        }
        Relationships: []
      }
      session_scores: {
        Row: {
          ai_feedback: string | null
          clarity_score: number | null
          communication_score: number | null
          confidence_score: number | null
          created_at: string
          id: string
          improvements: string[] | null
          interviewer_impression: string | null
          key_moments: Json | null
          overall_score: number | null
          relevance_score: number | null
          session_id: string
          star_usage_score: number | null
          strengths: string[] | null
          technical_depth: number | null
        }
        Insert: {
          ai_feedback?: string | null
          clarity_score?: number | null
          communication_score?: number | null
          confidence_score?: number | null
          created_at?: string
          id?: string
          improvements?: string[] | null
          interviewer_impression?: string | null
          key_moments?: Json | null
          overall_score?: number | null
          relevance_score?: number | null
          session_id: string
          star_usage_score?: number | null
          strengths?: string[] | null
          technical_depth?: number | null
        }
        Update: {
          ai_feedback?: string | null
          clarity_score?: number | null
          communication_score?: number | null
          confidence_score?: number | null
          created_at?: string
          id?: string
          improvements?: string[] | null
          interviewer_impression?: string | null
          key_moments?: Json | null
          overall_score?: number | null
          relevance_score?: number | null
          session_id?: string
          star_usage_score?: number | null
          strengths?: string[] | null
          technical_depth?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "session_scores_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: true
            referencedRelation: "interview_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      user_progress: {
        Row: {
          avg_score: number | null
          badges: Json | null
          created_at: string
          current_streak: number
          id: string
          last_session_at: string | null
          longest_streak: number
          total_hours: number
          total_sessions: number
          user_id: string
        }
        Insert: {
          avg_score?: number | null
          badges?: Json | null
          created_at?: string
          current_streak?: number
          id?: string
          last_session_at?: string | null
          longest_streak?: number
          total_hours?: number
          total_sessions?: number
          user_id: string
        }
        Update: {
          avg_score?: number | null
          badges?: Json | null
          created_at?: string
          current_streak?: number
          id?: string
          last_session_at?: string | null
          longest_streak?: number
          total_hours?: number
          total_sessions?: number
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_progress_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      user_resumes: {
        Row: {
          experience_years: number | null
          file_url: string | null
          id: string
          parsed_data: Json | null
          raw_text: string | null
          skills: string[] | null
          target_company_type: string | null
          target_role: string | null
          uploaded_at: string
          user_id: string
        }
        Insert: {
          experience_years?: number | null
          file_url?: string | null
          id?: string
          parsed_data?: Json | null
          raw_text?: string | null
          skills?: string[] | null
          target_company_type?: string | null
          target_role?: string | null
          uploaded_at?: string
          user_id: string
        }
        Update: {
          experience_years?: number | null
          file_url?: string | null
          id?: string
          parsed_data?: Json | null
          raw_text?: string | null
          skills?: string[] | null
          target_company_type?: string | null
          target_role?: string | null
          uploaded_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_resumes_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: Record<never, never>
    Functions: {
      reset_monthly_interviews: { Args: never; Returns: undefined }
    }
    Enums: {
      company_style:
        | "faang"
        | "startup"
        | "consulting"
        | "enterprise"
        | "agency"
        | "government"
      interview_type:
        | "behavioral"
        | "technical"
        | "case"
        | "hr"
        | "panel"
        | "phone_screen"
      message_role: "interviewer" | "candidate"
      session_length: "short" | "standard" | "deep"
      session_status: "in_progress" | "completed" | "abandoned" | "paused"
      subscription_status: "active" | "canceled" | "past_due" | "trialing"
      subscription_tier: "free" | "pro" | "premium"
    }
    CompositeTypes: Record<never, never>
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    // eslint-disable-next-line @typescript-eslint/no-redundant-type-constituents
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      company_style: [
        "faang",
        "startup",
        "consulting",
        "enterprise",
        "agency",
        "government",
      ],
      interview_type: [
        "behavioral",
        "technical",
        "case",
        "hr",
        "panel",
        "phone_screen",
      ],
      message_role: ["interviewer", "candidate"],
      session_length: ["short", "standard", "deep"],
      session_status: ["in_progress", "completed", "abandoned", "paused"],
      subscription_status: ["active", "canceled", "past_due", "trialing"],
      subscription_tier: ["free", "pro", "premium"],
    },
  },
} as const

// ============================================
// ENUM ALIASES (backwards compat for app code)
// ============================================
export type InterviewType = Database['public']['Enums']['interview_type'];
export type CompanyStyle = Database['public']['Enums']['company_style'];
export type SessionStatus = Database['public']['Enums']['session_status'];
export type MessageRole = Database['public']['Enums']['message_role'];
export type SubscriptionTier = Database['public']['Enums']['subscription_tier'];
export type SubscriptionStatus = Database['public']['Enums']['subscription_status'];

// Session length types for cost control
export type SessionLength = Database['public']['Enums']['session_length'];

export const SESSION_LENGTH_CONFIG: Record<SessionLength, {
  label: string;
  description: string;
  durationMinutes: number;
  maxUserMessages: number;
  questionRange: [number, number];
}> = {
  short: {
    label: 'Quick Practice',
    description: 'About 15 minutes',
    durationMinutes: 15,
    maxUserMessages: 10,
    questionRange: [5, 7],
  },
  standard: {
    label: 'Standard Mock',
    description: 'About 30 minutes',
    durationMinutes: 30,
    maxUserMessages: 20,
    questionRange: [8, 12],
  },
  deep: {
    label: 'Deep Dive',
    description: 'About 45 minutes',
    durationMinutes: 45,
    maxUserMessages: 30,
    questionRange: [12, 16],
  },
};

// ============================================
// ROW / INSERT / UPDATE ALIASES
// (backwards compat — used in explicit type
//  annotations throughout the codebase)
// ============================================

// -- Profiles --
export interface Profile {
  id: string;
  email: string;
  full_name: string | null;
  avatar_url: string | null;
  subscription_tier: SubscriptionTier;
  subscription_status: SubscriptionStatus;
  subscription_period_end: string | null;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  monthly_interviews_used: number;
  onboarding_completed: boolean;
  created_at: string;
  updated_at: string;
}

export interface ProfileInsert {
  id: string;
  email: string;
  full_name?: string | null;
  avatar_url?: string | null;
  subscription_tier?: SubscriptionTier;
  subscription_status?: SubscriptionStatus;
  subscription_period_end?: string | null;
  stripe_customer_id?: string | null;
  stripe_subscription_id?: string | null;
  monthly_interviews_used?: number;
  onboarding_completed?: boolean;
  created_at?: string;
  updated_at?: string;
}

export interface ProfileUpdate {
  email?: string;
  full_name?: string | null;
  avatar_url?: string | null;
  subscription_tier?: SubscriptionTier;
  subscription_status?: SubscriptionStatus;
  subscription_period_end?: string | null;
  stripe_customer_id?: string | null;
  stripe_subscription_id?: string | null;
  monthly_interviews_used?: number;
  onboarding_completed?: boolean;
  updated_at?: string;
}

// -- Interviewers --
export interface Interviewer {
  id: string;
  user_id: string;
  name: string;
  avatar_url: string | null;
  interview_type: InterviewType;
  company_style: CompanyStyle | null;
  role_focus: string | null;
  backstory: string | null;
  personality_base: PersonalityBase | null;
  difficulty_level: number;
  current_mood: InterviewerMood | null;
  voice_config: VoiceConfig | null;
  total_sessions: number;
  created_at: string;
}

export interface InterviewerInsert {
  id?: string;
  user_id: string;
  name: string;
  avatar_url?: string | null;
  interview_type: InterviewType;
  company_style?: CompanyStyle | null;
  role_focus?: string | null;
  backstory?: string | null;
  personality_base?: PersonalityBase | null;
  difficulty_level?: number;
  current_mood?: InterviewerMood | null;
  voice_config?: VoiceConfig | null;
  total_sessions?: number;
  created_at?: string;
}

export interface InterviewerUpdate {
  name?: string;
  avatar_url?: string | null;
  interview_type?: InterviewType;
  company_style?: CompanyStyle | null;
  role_focus?: string | null;
  backstory?: string | null;
  personality_base?: PersonalityBase | null;
  difficulty_level?: number;
  current_mood?: InterviewerMood | null;
  voice_config?: VoiceConfig | null;
  total_sessions?: number;
}

// -- Interviewer Personality --
export interface InterviewerPersonality {
  id: string;
  interviewer_id: string;
  communication_style: CommunicationStyle | null;
  question_patterns: QuestionPatterns | null;
  red_flags: string[] | null;
  green_flags: string[] | null;
  pet_peeves: string[] | null;
  favorite_topics: string[] | null;
  created_at: string;
}

export interface InterviewerPersonalityInsert {
  id?: string;
  interviewer_id: string;
  communication_style?: CommunicationStyle | null;
  question_patterns?: QuestionPatterns | null;
  red_flags?: string[] | null;
  green_flags?: string[] | null;
  pet_peeves?: string[] | null;
  favorite_topics?: string[] | null;
  created_at?: string;
}

export interface InterviewerPersonalityUpdate {
  communication_style?: CommunicationStyle | null;
  question_patterns?: QuestionPatterns | null;
  red_flags?: string[] | null;
  green_flags?: string[] | null;
  pet_peeves?: string[] | null;
  favorite_topics?: string[] | null;
}

// -- User Resumes --
export interface UserResume {
  id: string;
  user_id: string;
  raw_text: string | null;
  parsed_data: ParsedResumeData | null;
  skills: string[] | null;
  experience_years: number | null;
  target_role: string | null;
  target_company_type: string | null;
  file_url: string | null;
  uploaded_at: string;
}

export interface UserResumeInsert {
  id?: string;
  user_id: string;
  raw_text?: string | null;
  parsed_data?: ParsedResumeData | null;
  skills?: string[] | null;
  experience_years?: number | null;
  target_role?: string | null;
  target_company_type?: string | null;
  file_url?: string | null;
  uploaded_at?: string;
}

export interface UserResumeUpdate {
  raw_text?: string | null;
  parsed_data?: ParsedResumeData | null;
  skills?: string[] | null;
  experience_years?: number | null;
  target_role?: string | null;
  target_company_type?: string | null;
  file_url?: string | null;
}

// -- Interview Sessions --
export interface InterviewSession {
  id: string;
  user_id: string;
  interviewer_id: string;
  interview_type: InterviewType;
  target_role: string | null;
  target_company: string | null;
  difficulty: number;
  status: SessionStatus;
  started_at: string;
  ended_at: string | null;
  duration_seconds: number | null;
  voice_enabled: boolean;
  session_length: SessionLength | null;
  max_user_messages: number | null;
}

export interface InterviewSessionInsert {
  id?: string;
  user_id: string;
  interviewer_id: string;
  interview_type: InterviewType;
  target_role?: string | null;
  target_company?: string | null;
  difficulty?: number;
  status?: SessionStatus;
  started_at?: string;
  ended_at?: string | null;
  duration_seconds?: number | null;
  voice_enabled?: boolean;
  session_length?: SessionLength;
  max_user_messages?: number;
}

export interface InterviewSessionUpdate {
  interview_type?: InterviewType;
  target_role?: string | null;
  target_company?: string | null;
  difficulty?: number;
  status?: SessionStatus;
  ended_at?: string | null;
  duration_seconds?: number | null;
  voice_enabled?: boolean;
  session_length?: SessionLength;
  max_user_messages?: number;
}

// -- Interview Messages --
export interface InterviewMessage {
  id: string;
  session_id: string;
  role: MessageRole;
  content: string;
  audio_url: string | null;
  response_time_seconds: number | null;
  analysis: ResponseAnalysis | null;
  created_at: string;
}

export interface InterviewMessageInsert {
  id?: string;
  session_id: string;
  role: MessageRole;
  content: string;
  audio_url?: string | null;
  response_time_seconds?: number | null;
  analysis?: ResponseAnalysis | null;
  created_at?: string;
}

export interface InterviewMessageUpdate {
  content?: string;
  audio_url?: string | null;
  response_time_seconds?: number | null;
  analysis?: ResponseAnalysis | null;
}

// -- Session Scores --
export interface SessionScore {
  id: string;
  session_id: string;
  overall_score: number | null;
  clarity_score: number | null;
  confidence_score: number | null;
  technical_depth: number | null;
  star_usage_score: number | null;
  communication_score: number | null;
  relevance_score: number | null;
  strengths: string[] | null;
  improvements: string[] | null;
  ai_feedback: string | null;
  interviewer_impression: string | null;
  key_moments: KeyMoment[] | null;
  created_at: string;
}

export interface SessionScoreInsert {
  id?: string;
  session_id: string;
  overall_score?: number | null;
  clarity_score?: number | null;
  confidence_score?: number | null;
  technical_depth?: number | null;
  star_usage_score?: number | null;
  communication_score?: number | null;
  relevance_score?: number | null;
  strengths?: string[] | null;
  improvements?: string[] | null;
  ai_feedback?: string | null;
  interviewer_impression?: string | null;
  key_moments?: KeyMoment[] | null;
  created_at?: string;
}

export interface SessionScoreUpdate {
  overall_score?: number | null;
  clarity_score?: number | null;
  confidence_score?: number | null;
  technical_depth?: number | null;
  star_usage_score?: number | null;
  communication_score?: number | null;
  relevance_score?: number | null;
  strengths?: string[] | null;
  improvements?: string[] | null;
  ai_feedback?: string | null;
  interviewer_impression?: string | null;
  key_moments?: KeyMoment[] | null;
}

// -- User Progress --
export interface UserProgress {
  id: string;
  user_id: string;
  total_sessions: number;
  total_hours: number;
  current_streak: number;
  longest_streak: number;
  avg_score: number | null;
  badges: Badge[] | null;
  last_session_at: string | null;
  created_at: string;
}

export interface UserProgressInsert {
  id?: string;
  user_id: string;
  total_sessions?: number;
  total_hours?: number;
  current_streak?: number;
  longest_streak?: number;
  avg_score?: number | null;
  badges?: Badge[] | null;
  last_session_at?: string | null;
  created_at?: string;
}

export interface UserProgressUpdate {
  total_sessions?: number;
  total_hours?: number;
  current_streak?: number;
  longest_streak?: number;
  avg_score?: number | null;
  badges?: Badge[] | null;
  last_session_at?: string | null;
}

// ============================================
// JSON COLUMN TYPES
// ============================================
export interface PersonalityBase {
  directness: number;      // 0-100: How blunt vs. diplomatic
  depth_preference: number; // 0-100: Surface vs. deep dives
  warmth: number;          // 0-100: Cold vs. friendly
  patience: number;        // 0-100: Quick follow-ups vs. letting you think
  technical_focus: number; // 0-100: Soft skills vs. hard skills
  skepticism: number;      // 0-100: Trusting vs. needs proof
}

export interface InterviewerMood {
  current: 'impressed' | 'neutral' | 'skeptical' | 'critical' | 'engaged';
  intensity: number; // 0-100
  triggers: string[];
}

export interface VoiceConfig {
  voice_id: string;
  speed: number;
  pitch: number;
  tts_enabled?: boolean;
}

export interface CommunicationStyle {
  style: 'direct' | 'probing' | 'supportive' | 'challenging';
  formality: number; // 0-100
  verbosity: number; // 0-100
}

export interface QuestionPatterns {
  follow_up_tendency: number; // 0-100
  depth_preference: number;   // 0-100
  curveball_frequency: number; // 0-100
}

export interface ParsedResumeData {
  name?: string;
  email?: string;
  phone?: string;
  location?: string;
  summary?: string;
  experience: WorkExperience[];
  education: Education[];
  skills: string[];
  certifications?: string[];
}

export interface WorkExperience {
  company: string;
  title: string;
  start_date: string;
  end_date: string | null;
  description: string;
  highlights: string[];
}

export interface Education {
  institution: string;
  degree: string;
  field: string;
  graduation_date: string;
}

export interface ResponseAnalysis {
  star_score: number;
  clarity_score: number;
  confidence_score: number;
  relevance_score: number;
  depth_score: number;
  word_count: number;
  filler_words: string[];
  key_points: string[];
}

export interface KeyMoment {
  timestamp: number;
  type: 'strong' | 'weak' | 'turning_point';
  description: string;
  message_id?: string;
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  earned_at: string;
}

// ============================================
// JOINED TYPES
// ============================================
export interface InterviewerWithPersonality extends Interviewer {
  interviewer_personality: InterviewerPersonality | null;
}

export interface SessionWithDetails extends InterviewSession {
  interviewers: Pick<Interviewer, 'id' | 'name' | 'avatar_url' | 'interview_type'>;
  session_scores: SessionScore | null;
}

export interface SessionWithMessages extends InterviewSession {
  interview_messages: InterviewMessage[];
}
