/**
 * Supabase Storage Helper
 *
 * Handles file uploads for resumes.
 *
 * SETUP: Create bucket in Supabase Dashboard:
 * 1. "resumes" — for resume PDF/text uploads (bucket must be PRIVATE, not public)
 *
 * IMPORTANT: The resumes bucket must NOT have public access enabled.
 * Resume files contain full PII (name, email, phone, address, work history).
 * Access is granted per-request via short-lived signed URLs generated by
 * getResumeSignedUrl(), never via permanent public URLs.
 */

import { type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '@/types/database';

const RESUME_BUCKET = 'resumes';
const MAX_RESUME_SIZE = 5 * 1024 * 1024; // 5MB

/** Default signed URL TTL: 1 hour */
const SIGNED_URL_TTL_SECONDS = 3600;

/**
 * Authoritative extension per accepted MIME type. We derive the storage-path
 * extension from the verified MIME rather than the client-supplied filename —
 * browsers populate File.name with arbitrary strings and using
 * `file.name.split('.').pop()` leaves the stored path exposed to weird tokens
 * (URL-encoded bytes, traversal fragments, mis-cased or nested extensions).
 * Supabase Storage does normalise paths, but sourcing ext from the MIME
 * whitelist removes the entire filename-trust step.
 */
const EXT_BY_MIME: Record<string, string> = {
  'application/pdf': 'pdf',
  'text/plain': 'txt',
  'application/msword': 'doc',
  'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'docx',
};

export interface UploadResult {
  success: boolean;
  /** Storage path within the resumes bucket (e.g. "{userId}/{ts}-resume.pdf").
   *  Use getResumeSignedUrl() to obtain a short-lived download URL from this path.
   *  Never stored as a public URL. */
  path?: string;
  error?: string;
}

export interface SignedUrlResult {
  success: boolean;
  signedUrl?: string;
  error?: string;
}

/**
 * Upload a resume file to Supabase Storage.
 *
 * Returns only the storage path — no public URL is generated.
 * Call getResumeSignedUrl() when a download link is actually needed.
 */
export async function uploadResume(
  supabase: SupabaseClient<Database>,
  userId: string,
  file: File
): Promise<UploadResult> {
  if (file.size > MAX_RESUME_SIZE) {
    return { success: false, error: 'File size exceeds 5MB limit' };
  }

  const allowedTypes = [
    'application/pdf',
    'text/plain',
    'application/msword',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  ];

  if (!allowedTypes.includes(file.type)) {
    return { success: false, error: 'Only PDF, TXT, DOC, and DOCX files are allowed' };
  }

  const timestamp = Date.now();
  // Source the extension from the validated MIME, not from the client-supplied
  // filename. Falls back to 'pdf' for any MIME slip-through (allowedTypes is
  // already enforced above, so this branch is defence-in-depth).
  const ext = EXT_BY_MIME[file.type] ?? 'pdf';
  const filePath = `${userId}/${timestamp}-resume.${ext}`;

  try {
    const { data, error } = await supabase.storage
      .from(RESUME_BUCKET)
      .upload(filePath, file, {
        cacheControl: '3600',
        upsert: true,
      });

    if (error) {
      console.error('[Storage] Resume upload error:', error);
      return { success: false, error: error.message };
    }

    return {
      success: true,
      path: data.path,
    };
  } catch (error) {
    console.error('[Storage] Resume upload failed:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Upload failed',
    };
  }
}

/**
 * Generate a short-lived signed URL for a resume file.
 *
 * Use this any time you need to let the authenticated user download or
 * preview their own resume. The URL expires after ttlSeconds (default 1 hour)
 * and is not shareable.
 */
export async function getResumeSignedUrl(
  supabase: SupabaseClient<Database>,
  storagePath: string,
  ttlSeconds = SIGNED_URL_TTL_SECONDS
): Promise<SignedUrlResult> {
  try {
    const { data, error } = await supabase.storage
      .from(RESUME_BUCKET)
      .createSignedUrl(storagePath, ttlSeconds);

    if (error || !data?.signedUrl) {
      console.error('[Storage] Failed to create signed URL:', error);
      return { success: false, error: error?.message ?? 'Failed to generate download link' };
    }

    return { success: true, signedUrl: data.signedUrl };
  } catch (error) {
    console.error('[Storage] Signed URL generation failed:', error);
    return {
      success: false,
      error: error instanceof Error ? error.message : 'Failed to generate download link',
    };
  }
}
